name: Build and Deploy docker images to cloud

on: push

jobs:
      
  deploy-sc:
    
    runs-on: ubuntu-latest
    name: Deploy to scaleway
    env:
      REGION: fr-par
      REGISTRY_URL: rg.fr-par.scw.cloud/funcscwynovmwg0m0ur
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get image name
        run: |
          VERSION=${GITHUB_REF#refs/*/}
          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
            IMAGE_TAG=$GITHUB_HEAD_REF
          elif [ "$VERSION" == "master" ]; then
            IMAGE_TAG=latest
          else
            IMAGE_TAG=$VERSION
          fi
          echo "DOCKER_IMAGE=${{ secrets.DOCKER_USER }}/secure:$GITHUB_SHA" >> $GITHUB_ENV
      - name: Build docker image
        run: >-
          docker build docker/secure
          --tag $DOCKER_IMAGE
      - run: docker push $DOCKER_IMAGE
      
      - uses: actions/checkout@v2
      - name: Login to Scaleway Container Registry
        run: docker login $REGISTRY_URL --username nologin --password ${{ secrets.SCALEWAY_SECRET_KEY }}
      - name: tag image
        run: docker tag ${{ secrets.DOCKER_USER }}/secure:$GITHUB_SHA ${{ env.REGISTRY_URL }}/ynov-secure:latest
      - name: Push image to registry
        run: docker push ${{ env.REGISTRY_URL }}/ynov-secure:latest
      
      - name: list instances
        uses: jawher/action-scw@v2.5.4
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCALEWAY_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCALEWAY_SECRET_KEY }}
          SCW_ORGANIZATION_ID: ${{ secrets.SCALEWAY_ORGANIZATION_ID }}
          SCW_ZONE: fr-par-1
          NAMESPACE_ID: 861546b0-d851-471c-87db-4b23b7f87256
        with:
          args: container container list -o=json
      
      - name: Get instance id and expose it in INSTANCE_ID env var
        run: echo "CONTAINER_ID=$(cat "${GITHUB_WORKSPACE}/scw.output" | jq -r '.[0].id')" >> $GITHUB_ENV
      
      - name: deploy instance
        uses: jawher/action-scw@v2.5.4
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCALEWAY_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCALEWAY_SECRET_KEY }}
          SCW_ORGANIZATION_ID: ${{ secrets.SCALEWAY_ORGANIZATION_ID }}
          SCW_ZONE: fr-par-1
        with:
          args: container container update ${{ env.CONTAINER_ID }} port=5000 registry-image=${{ env.REGISTRY_URL }}/ynov-secure:latest -o=json
      
#https://github.com/scaleway/scaleway-cli/blob/master/docs/commands/container.md#container-management-commands
